fs/notify: Fix incompatible function pointer in fanotify_fdinfo
The integration of SUSFS modifies show_fdinfo() to pass an additional
'struct file *' argument. However, fanotify_fdinfo() was unconditionally
defined to accept three arguments, causing a build failure when
CONFIG_KSU_SUSFS_SUS_MOUNT is disabled (or mismatching the expected
callback signature).

This caused the following error:
error: incompatible function pointer types passing 'void (..., struct file *)'
to parameter of type 'void (*)(..., struct fsnotify_mark *)'

This commit adds the necessary #ifdef guards to fanotify_fdinfo()
definition to ensure the function signature matches what show_fdinfo()
expects in both configurations.

Signed-off-by: key13bb <key13bb@gmail.com>